sudo: required
services:
  -docker

before_install:
    # docker build -tag <name-of-the-image> -f<file> <build context>
  - docker build -t aminux/react-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aminux/react-client npm run test

after_success:
  - docker build -t aminux/fib-client ./client
  - docker build -t aminux/fib-server ./server
  - docker build -t aminux/fib-worker ./worker
  - docker build -t aminux/fib-nginx ./nginx
  # We need to login to docker CLI - we add username and password 
  # to travis as an environment variable under the project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin # take password as an input to the next command 
  - docker push aminux/fib-client
  - docker push aminux/fib-server
  - docker push aminux/fib-worker
  - docker push aminux/fib-nginx


